"""add upi number to students

Revision ID: 7e7591f7ce11
Revises: b26766be4570
Create Date: 2026-09-13 18:13:38.302657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e7591f7ce11'
down_revision: Union[str, Sequence[str], None] = 'b26766be4570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('upi_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'upi_number')
    # ### end Alembic commands ###
